name: recipe
description: Store your recipes and see what others are up to on our application
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  bloc_concurrency: ^0.2.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.6
  get_it: ^7.6.0
  injectable: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dart_code_metrics: ^5.7.4
  injectable_generator: ^2.1.5
  build_runner: ^2.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/svg/
  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/SFProText-Regular.otf
          weight: 400
        - asset: assets/fonts/SFProText-Medium.otf
          weight: 500
        - asset: assets/fonts/SFProText-Semibold.otf
          weight: 600