name: recipe
description: Store your recipes and see what others are up to on our application
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  auto_route: ^7.3.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.6
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  google_sign_in: ^6.1.2
  injectable: ^2.1.1
  uuid: ^3.0.7

dev_dependencies:
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.4
  dart_code_metrics: ^5.7.4
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  injectable_generator: ^2.1.5
  lorem_ipsum: ^0.0.3
  objectbox_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/svg/
  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/SFProText-Regular.otf
          weight: 400
        - asset: assets/fonts/SFProText-Medium.otf
          weight: 500
        - asset: assets/fonts/SFProText-Semibold.otf
          weight: 600
