name: recipe
description: Store your recipes and see what others are up to on our application
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dart_code_metrics: ^5.7.4

flutter:
  uses-material-design: true
  assets:
    - assets/fonts
  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/SFProText-Regular.otf
          weight: 400
        - asset: assets/fonts/SFProText-Medium.otf
          weight: 500
        - asset: assets/fonts/SFProText-Semibold.otf
          weight: 600