name: recipe_service
description: Store your recipes and see what others are up to on our application
publish_to: 'none'
version: 0.2.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  awesome_bottom_bar: ^1.2.2
  cloud_firestore: ^4.8.0
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.6
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  google_sign_in: ^6.1.2
  hive: ^2.2.3
  injectable: ^2.1.1
  kt_dart: ^1.1.0
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.4.4
  dart_code_metrics: ^5.7.4
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/svg/
  fonts:
    - family: SF-Pro
      fonts:
        - asset: assets/fonts/SF-Pro.ttf